name        'lynxman/hiera_consul'
version     '0.0.2'
source      'git://github.com/lynxman/hiera-consul.git'
author      'Marc Cluet'
summary     'Module for using consul as a hiera backend'
description 'Use consul by Hashicorp, as a hiera backend'
license     'Apache License, Version 2.0'
